<a href="https://colab.research.google.com/github/Tanisha2054/DV-Tasks/blob/main/task3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [24]:
df = pd.read_csv('train.csv')

In [4]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [5]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [6]:
df = df.dropna()

In [13]:
df.Ticket[3], df.Embarked[3]

('113803', 'S')

In [10]:
df.Ticket

1      PC 17599
3        113803
6         17463
10      PP 9549
11       113783
         ...
871       11751
872         695
879       11767
887      112053
889      111369
Name: Ticket, Length: 183, dtype: object

In [ ]:
df= df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 183 entries, 1 to 889
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  183 non-null    int64
 1   Survived     183 non-null    int64
 2   Pclass       183 non-null    int64
 3   Name         183 non-null    object
 4   Sex          183 non-null    object
 5   Age          183 non-null    float64
 6   SibSp        183 non-null    int64
 7   Parch        183 non-null    int64
 8   Ticket       183 non-null    object
 9   Fare         183 non-null    float64
 10  Cabin        183 non-null    object
 11  Embarked     183 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 18.6+ KB

In [15]:
df.Embarked.unique()

array(['C', 'S', 'Q'], dtype=object)

In [17]:
df.corr()

<ipython-input-17-2f6f6606aa2c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,0.148495,-0.089136,0.030933,-0.083488,-0.051454,0.029740
Survived,0.148495,1.000000,-0.034542,-0.254085,0.106346,0.023582,0.134241
Pclass,-0.089136,-0.034542,1.000000,-0.306514,-0.103592,0.047496,-0.315235
Age,0.030933,-0.254085,-0.306514,1.000000,-0.156162,-0.271271,-0.092424
SibSp,-0.083488,0.106346,-0.103592,-0.156162,1.000000,0.255346,0.286433
Parch,-0.051454,0.023582,0.047496,-0.271271,0.255346,1.000000,0.389740
Fare,0.029740,0.134241,-0.315235,-0.092424,0.286433,0.389740,1.000000

In [18]:
df.Cabin.unique()

array(['C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6', 'C23 C25 C27',
       'D33', 'B30', 'C83', 'F33', 'F G73', 'E31', 'A5', 'D10 D12', 'D26',
       'C110', 'B58 B60', 'E101', 'D47', 'B86', 'F2', 'C2', 'B19', 'A7',
       'C49', 'F4', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'B49',
       'D', 'C22 C26', 'C65', 'E36', 'C54', 'B57 B59 B63 B66', 'C7',
       'E34', 'C32', 'B18', 'C124', 'C91', 'E40', 'T', 'E33', 'D37',
       'B35', 'E50', 'C82', 'B96 B98', 'E10', 'C52', 'E44', 'A34', 'C104',
       'C111', 'C92', 'E38', 'E12', 'E63', 'B37', 'C30', 'D20', 'B79',
       'E25', 'D46', 'B73', 'B38', 'B39', 'B22', 'C86', 'C70', 'A16',
       'C101', 'C68', 'A10', 'E68', 'B41', 'A20', 'D19', 'D50', 'D9',
       'A23', 'B50', 'A26', 'D48', 'E58', 'B71', 'B51 B53 B55', 'D49',
       'B5', 'B20', 'F G63', 'C62 C64', 'E24', 'C90', 'C126', 'C45', 'E8',
       'B101', 'C46', 'D30', 'E121', 'D11', 'E77', 'B3', 'D6', 'B82 B84',
       'D17', 'A36', 'B69', 'E49', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148'], dtype=object)

In [19]:
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler

In [25]:
def HandleTkt(value):
    values=value.split(' ')[-1]
    return value
def HandleSex(value):
    if value=="male":
        value=1
    else:
        value=0
    return value
def Preprocessing(df):
    df.Sex=df.Sex.astype(str)
    df.Sex=df.Sex.apply(HandleSex)
    df.Sex=df.Sex.astype(int)
    df.Age=df.Age.fillna(df.Age.median())
    df.Embarked=df.Embarked.astype(str)
    df.Embarked[(df.Embarked.isna())]==""
    df['Embarked:S']=0
    df['Embarked:C']=0
    df['Embarked:Q']=0
    for i in range(0,len(df)):
        if df.Embarked[i]=="S":
            df['Embarked:S'][i]=1
        if df.Embarked[i]=="C":
            df['Embarked:C'][i]=1
        if df.Embarked[i]=="Q":
            df['Embarked:Q'][i]=1
    df.Ticket=df.Ticket.astype(str)
    df.Ticket=df.Ticket.drop(df.Ticket[(df.Ticket=="LINE")].index,axis=0)
    df.reset_index()
    for i in range (0, len(df)):
        try:
            df.Ticket[i]=float(df.Ticket[i].split()[-1])
        except:
            print(str(i)+" - "+ str(df.Ticket[i]))

    df.Ticket=df.Ticket.astype(float)
    df.Ticket=df.Ticket.fillna(df.Ticket.median())
    df=df.drop(columns=['Cabin','Name','Embarked'],axis=1)
    df=df.drop(columns=["Age","SibSp","Parch"],axis=1)
    return df

In [26]:
train_df=Preprocessing(df)

<ipython-input-25-4b051e49e011>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Embarked:S'][i]=1
<ipython-input-25-4b051e49e011>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Embarked:C'][i]=1
<ipython-input-25-4b051e49e011>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Embarked:Q'][i]=1
<ipython-input-25-4b051e49e011>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Ticket[i]=float(df.Ticket[i].split()[-1])

179 - nan
271 - nan
302 - nan
597 - nan

In [37]:
df.Cabin.unique()

array(['n', 'C', 'E', 'G', 'D', 'A', 'B', 'F', 'T'], dtype=object)

In [36]:
for i in range(len(df)):
  try:
    df.Cabin[i]=str(df.Cabin[i])[0]
  except:
    print(i)

<ipython-input-36-cc42e8dd3ed3>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Cabin[i]=str(df.Cabin[i])[0]

In [38]:
df.corr()

<ipython-input-38-2f6f6606aa2c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked:S,Embarked:C,Embarked:Q
PassengerId,1.000000,-0.005007,-0.035144,0.042939,0.034212,-0.057527,-0.001652,-0.022428,0.012658,0.022148,-0.001205,-0.033606
Survived,-0.005007,1.000000,-0.338481,-0.543351,-0.064910,-0.035322,0.081629,-0.095844,0.257307,-0.155660,0.168240,0.003650
Pclass,-0.035144,-0.338481,1.000000,0.131900,-0.339898,0.083081,0.018443,0.284732,-0.549500,0.081720,-0.243292,0.221009
Sex,0.042939,-0.543351,0.131900,1.000000,0.081163,-0.114631,-0.245489,0.076282,-0.182333,0.125722,-0.082853,-0.074115
Age,0.034212,-0.064910,-0.339898,0.081163,1.000000,-0.233296,-0.172482,-0.100123,0.096688,-0.014665,0.030248,-0.031415
SibSp,-0.057527,-0.035322,0.083081,-0.114631,-0.233296,1.000000,0.414838,0.046591,0.159651,0.070941,-0.059528,-0.026354
Parch,-0.001652,0.081629,0.018443,-0.245489,-0.172482,0.414838,1.000000,-0.032903,0.216225,0.063036,-0.011069,-0.081228
Ticket,-0.022428,-0.095844,0.284732,0.076282,-0.100123,0.046591,-0.032903,1.000000,-0.155913,0.172748,-0.193857,-0.003093
Fare,0.012658,0.257307,-0.549500,-0.182333,0.096688,0.159651,0.216225,-0.155913,1.000000,-0.166603,0.269335,-0.117216
Embarked:S,0.022148,-0.155660,0.081720,0.125722,-0.014665,0.070941,0.063036,0.172748,-0.166603,1.000000,-0.778359,-0.496624
Embarked:C,-0.001205,0.168240,-0.243292,-0.082853,0.030248,-0.059528,-0.011069,-0.193857,0.269335,-0.778359,1.000000,-0.148258
Embarked:Q,-0.033606,0.003650,0.221009,-0.074115,-0.031415,-0.026354,-0.081228,-0.003093,-0.117216,-0.496624,-0.148258,1.000000

In [33]:
df[df.Survived==0].describe()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked:S,Embarked:C,Embarked:Q
count,342.000000,342.0,342.000000,342.000000,342.000000,342.000000,342.000000,3.420000e+02,342.000000,342.000000,342.000000,342.000000
mean,444.368421,1.0,1.950292,0.318713,28.291433,0.473684,0.464912,2.178469e+05,48.395408,0.634503,0.271930,0.087719
std,252.358840,0.0,0.863321,0.466660,13.764425,0.708688,0.771712,5.659174e+05,66.596998,0.482275,0.445606,0.283301
min,2.000000,1.0,1.000000,0.000000,0.420000,0.000000,0.000000,5.410000e+02,0.000000,0.000000,0.000000,0.000000
25%,250.750000,1.0,1.000000,0.000000,21.000000,0.000000,0.000000,1.431225e+04,12.475000,0.000000,0.000000,0.000000
50%,439.500000,1.0,2.000000,0.000000,28.000000,0.000000,0.000000,3.122250e+04,26.000000,1.000000,0.000000,0.000000
75%,651.500000,1.0,3.000000,1.000000,35.000000,1.000000,1.000000,2.438718e+05,57.000000,1.000000,1.000000,0.000000
max,890.000000,1.0,3.000000,1.000000,80.000000,4.000000,5.000000,3.101298e+06,512.329200,1.000000,1.000000,1.000000

In [34]:
df[df.Survived==1].describe()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked:S,Embarked:C,Embarked:Q
count,342.000000,342.0,342.000000,342.000000,342.000000,342.000000,342.000000,3.420000e+02,342.000000,342.000000,342.000000,342.000000
mean,444.368421,1.0,1.950292,0.318713,28.291433,0.473684,0.464912,2.178469e+05,48.395408,0.634503,0.271930,0.087719
std,252.358840,0.0,0.863321,0.466660,13.764425,0.708688,0.771712,5.659174e+05,66.596998,0.482275,0.445606,0.283301
min,2.000000,1.0,1.000000,0.000000,0.420000,0.000000,0.000000,5.410000e+02,0.000000,0.000000,0.000000,0.000000
25%,250.750000,1.0,1.000000,0.000000,21.000000,0.000000,0.000000,1.431225e+04,12.475000,0.000000,0.000000,0.000000
50%,439.500000,1.0,2.000000,0.000000,28.000000,0.000000,0.000000,3.122250e+04,26.000000,1.000000,0.000000,0.000000
75%,651.500000,1.0,3.000000,1.000000,35.000000,1.000000,1.000000,2.438718e+05,57.000000,1.000000,1.000000,0.000000
max,890.000000,1.0,3.000000,1.000000,80.000000,4.000000,5.000000,3.101298e+06,512.329200,1.000000,1.000000,1.000000